### ISSUE TITLE
Add rss support

### ISSUE THREAD

**Issue by mkeedlinger** [janka102/webmonitor#3]
So changes can be read via a feed reader instead of email.

**Comment by janka102** [comment]
Good idea, that'll be cool to figure out how to do that

**Comment by janka102** [comment]
I added a PR in #4, but it seems some Readers break when viewing the content, I'll look into that.

**Comment by mkeedlinger** [comment]
What did you see?

**Comment by janka102** [comment]
From what I remember I didn't find any way to fix those couple broken readers. But I guess I'll just merge it in and if there's really any issues when using it I can dig deeper then

**Comment by janka102** [comment]
Done in #4
